field_mappings = {
    "START": {
        1: "Record Type",
        2: "Gateway Name",
        3: "Accounting ID",
        4: "Start Time in System Ticks",
        5: "Node Time Zone",
        6: "Start Time (Date)",
        7: "Start Time (Time)",
        8: "Time Elapsed from Receipt of Setup Message to Policy Server/SoftSwitch Response",
        9: "Time Elapsed from Receipt of Setup Message to Receipt of Alerting/ProcProg",
        10: "Time Elapsed from Receipt of Setup Message to Service Established",
        11: "Service Delivered",
        12: "Call Direction",
        13: "Service Provider",
        14: "Transit Network Selection Code",
        15: "Calling Number",
        16: "Called Number",
        17: "Extra Called Address Digits",
        18: "Number of Called Num Translations Done by This Node",
        19: "Called Number Before Translation #1",
        20: "Translation Type 1",
        21: "Called Number Before Translation #2",
        22: "Translation Type 2",
        23: "Billing Number",
        24: "Route Label",
        25: "Route Attempt Number",
        26: "Route Selected",
        27: "Egress Local Gateway Signaling IP Address",
        28: "Egress Remote Gateway Signaling IP Address",
        29: "Ingress Trunk Group Name",
        30: "Ingress PSTN Circuit End Point",
        31: "Ingress IP Circuit End Point",
        32: "Egress PSTN Circuit End Point",
        33: "Egress IP Circuit End Point",
        34: "Originating Line Information (OLIP)",
        35: "Jurisdiction Information Parameter",
        36: "Carrier Code",
        37: "Call Group ID",
        38: "Time Elapsed from Receipt of Setup Message to Receipt of Exit Message",
        39: "Time Elapsed from Receipt of Setup Message to Generation of Exit Message",
        40: "Calling Party Nature of Address",
        41: "Called Party Nature of Address",
        42: "Ingress Protocol Variant Specific Data",
        43: "Ingress Signaling Type",
        44: "Egress Signaling Type",
        45: "Ingress Far End Switch Type",
        46: "Egress Far End Switch Type",
        47: "Far End Ingress TG Carrier Code",
        48: "Far End Egress TG Carrier Code",
        49: "Calling Party Category",
        50: "Dialed Number",
        51: "Carrier Selection Information",
        52: "Called Number Numbering Plan",
        53: "Generic Address Parameter",
        54: "Egress Trunk Group Name",
        55: "Egress Protocol Variant Specific Data",
        56: "Incoming Calling Number",
        57: "AMA Call Type",
        58: "Message Billing Index (MBI)",
        59: "Originating LATA",
        60: "Route Index Used",
        61: "Calling Party Number Presentation Restriction",
        62: "Incoming ISUP Charge Number",
        63: "Incoming ISUP Charge Number NOA",
        64: "Dialed Number NOA",
        65: "SBC Call ID",
        66: "Charge Flag",
        67: "AMA Service Logic Identification",
        68: "AMA BAF Module",
        69: "AMA Set Hex AB Indication",
        70: "Service Feature ID",
        71: "FE Parameter",
        72: "Satellite Indicator",
        73: "PSX Billing Information",
        74: "Originating TDM Trunk Group Type",
        75: "Terminating TDM Trunk Group Type",
        76: "Ingress Trunk Member Number",
        77: "Egress Trunk Group ID",
        78: "Egress Switch ID",
        79: "Ingress Local ATM Address",
        80: "Ingress Remote ATM Address",
        81: "Egress Local ATM Address",
        82: "Egress Remote ATM Address",
        83: "Policy Response Call Type",
        84: "Outgoing Route Identification",
        85: "Outgoing Message Identification",
        86: "Incoming Route Identification",
        87: "Calling Name",
        88: "Calling Name Type",
        89: "Incoming Calling Party Numbering Plan",
        90: "Outgoing Calling Party Numbering Plan",
        91: "Calling Party Business Group ID",
        92: "Called Party Business Group ID",
        93: "Calling Party Public Presence Directory Number",
        94: "Elapsed Time from Receipt of Setup Message to Last Call Routing Attempt",
        95: "Billing Number NOA",
        96: "Incoming Calling Number NOA",
        97: "Egress Trunk Member Number",
        98: "Selected Route Type",
        99: "Cumulative Route Index",
        100: "ISDN PRI Calling Party Subaddress",
        101: "Outgoing Trunk Group Number in EXM",
        102: "Ingress Local Gateway Signaling IP Address",
        103: "Ingress Remote Gateway Signaling IP Address",
        104: "Record Sequence Number",
        105: "Transmission Medium Requirement (TMR)",
        106: "Information Transfer Rate (ITR)",
        107: "User Service Information (USI) User Information Layer 1",
        108: "Unrecognized Raw ISUP Calling Party Category",
        109: "Egress RLT Feature Specific Data",
        110: "Two B-Channel Transfer Feature Specific Data",
        111: "Calling Party Business Unit",
        112: "Called Party Business Unit",
        113: "Redirection Feature Specific Data",
        114: "Ingress RLT Feature Specific Data",
        115: "PSX Index",
        116: "PSX Congestion Level",
        117: "PSX Processing Time",
        118: "Script Name",
        119: "Ingress External Accounting Data",
        120: "Egress External Accounting Data",
        121: "Answer Supervision Type",
        122: "Ingress SIP REFER and Replaces Feature Specific Data",
        123: "Egress SIP REFER and Replaces Feature Specific Data",
        124: "Network Transfer Feature Specific Data",
        125: "Call Condition",
        126: "Toll Indicator",
        127: "Generic Number (Number)",
        128: "Generic Number (Presentation Restriction Indicator)",
        129: "Generic Number (Numbering Plan)",
        130: "Generic Number (Nature of Address)",
        131: "Generic Number (Type)",
        132: "Originating Trunk Type",
        133: "Terminating Trunk Type",
        134: "VPN Calling Private Presence Number",
        135: "VPN Calling Public Presence Number",
        136: "External Furnish Charging Info",
        137: "Announcement ID",
        138: "Source Information",
        139: "Partition ID",
        140: "Network ID",
        141: "NCOS",
        142: "ISDN Access Indicator from the Forward Call Indicator",
        143: "Network Call Reference - Call Identity",
        144: "Network Call Reference - Signaling Point Code",
        145: "Ingress ISUP MIME Protocol Variant Specific Data",
        146: "Egress ISUP MIME Protocol Variant Specific Data",
        147: "Video Codec Data",
        148: "SVS Customer",
        149: "SVS Vendor (deprecated)",
        150: "Remote SBC Billing Indicator",
        151: "Call to Test PSX",
        152: "PSX Overlap Route Requests",
        153: "Call Setup Delay",
        154: "Overload Status",
        155: "RESERVED (Ingress Bicc Info)",
        156: "RESERVED (Egress Bicc Info)",
        157: "MLPP Precedence Level",
        158: "RESERVED (MSRP Service Type)",
        159: "RESERVED (NPUKK Special Routing Information)",
        160: "RESERVED (NPUKK Customer Or Carrier Identification)",
        161: "RESERVED (NPUKK ServiceType Identifier)",
        162: "RESERVED (NPSSP Special Handling Information)",
        163: "RESERVED (NPSSP Service Type Identifier)",
        164: "RESERVED (ONI Str)",
        165: "RESERVED (Suppress ONI)",
        166: "Global Charge Reference (GCR)",
        167: "RESERVED (IP Call Limit at ingress SIP Peer)",
        168: "RESERVED (IP Call Limit at ingress IPTG)",
        169: "RESERVED (IP BW Limit at ingress IPTG)",
        170: "RESERVED (IP Call Limit at egress SIP Peer)",
        171: "RESERVED (IP Call Limit at egress IPTG)",
        172: "RESERVED (IP BW Limit at egress IPTG)",
        173: "RESERVED (PSX Name)",
        174: "RESERVED (No. of PSX tried)",
        175: "Final Route Label",
        176: "MTA Information",
        177: "Access Network Charging Information",
        178: "Access Transfer Specific Data",
        179: "Emergency Indicator",
        180: "UE Roaming Status",
        181: "Ingress Zone Name",
        182: "Egress Zone Name",
        183: "Ingress Zone Id",
        184: "Egress Zone Id",
        185: "Ingress IP Prefix Found TG Name",
        186: "Forking Call Parent GCID",
        187: "SO-SBC",
        188: "Call Established Time",
        189: "Ingress Trunk Group for PSX Routing",
        190: "Start Time (Local)",
        191: "Call Established Time (Local)",
    },
    "STOP": {
    1: "Record Type",
    2: "Gateway Name",
    3: "Accounting ID",
    4: "Start Time in System Ticks",
    5: "Node Time Zone",
    6: "Start Time (Date)",
    7: "Start Time (Time)",
    8: "Time Elapsed from Receipt of Setup Message to Policy Server/SoftSwitch Response",
    9: "Time Elapsed from Receipt of Setup Message to Receipt of Alerting/ProcProg",
    10: "Time Elapsed from Receipt of Setup Message to Service Established",
    11: "Disconnect Time (Date)",
    12: "Disconnect Time (Time)",
    13: "Time Elapsed from Receipt of Disconnect to Completion of Call",
    14: "Call Service Duration",
    15: "Call Disconnect Reason",
    16: "Service Delivered",
    17: "Call Direction",
    18: "Service Provider",
    19: "Transit Network Selection Code",
    20: "Calling Number",
    21: "Called Number",
    22: "Extra Called Address Digits",
    23: "Number of Called Num Translations Done by This Node",
    24: "Called Number Before Translation #1",
    25: "Translation Type 1",
    26: "Called Number Before Translation #2",
    27: "Translation Type 2",
    28: "Billing Number",
    29: "Route Label",
    30: "Route Attempt Number",
    31: "Route Selected",
    32: "Egress Local Gateway Signaling IP Address",
    33: "Egress Remote Gateway Signaling IP Address",
    34: "Ingress Trunk Group Name",
    35: "Ingress PSTN Circuit End Point",
    36: "Ingress IP Circuit End Point",
    37: "Egress PSTN Circuit End Point",
    38: "Egress IP Circuit End Point",
    39: "Ingress Number of Audio Bytes Sent",
    40: "Ingress Number of Audio Packets Sent",
    41: "Ingress Number of Audio Bytes Received",
    42: "Ingress Number of Audio Packets Received",
    43: "Originating Line Information (OLIP)",
    44: "Jurisdiction Information Parameter",
    45: "Carrier Code",
    46: "Call Group ID",
    47: "Script Log Data",
    48: "Time Elapsed from Receipt of Setup Message to Receipt of Exit Message",
    49: "Time Elapsed from Receipt of Setup Message to Generation of Exit Message",
    50: "Calling Party Nature of Address",
    51: "Called Party Nature of Address",
    52: "Ingress Protocol Variant Specific Data",
    53: "Ingress Signaling Type",
    54: "Egress Signaling Type",
    55: "Ingress Far End Switch Type",
    56: "Egress Far End Switch Type",
    57: "Far End Ingress TG Carrier Code",
    58: "Far End Egress TG Carrier Code",
    59: "Calling Party Category",
    60: "Dialed Number",
    61: "Carrier Selection Information",
    62: "Called Number Numbering Plan",
    63: "Generic Address Parameter",
    64: "Disconnect Initiator",
    65: "Ingress Number of Packets Recorded as Lost",
    66: "Ingress Interarrival Packet Jitter",
    67: "Ingress Last Measurement for Latency",
    68: "Egress Trunk Group Name",
    69: "Egress Protocol Variant Specific Data",
    70: "Incoming Calling Number",
    71: "AMA Call Type",
    72: "Message Billing Index (MBI)",
    73: "Originating LATA",
    74: "Route Index Used",
    75: "Calling Party Number Presentation Restriction",
    76: "Incoming ISUP Charge Number",
    77: "Incoming ISUP Charge Number NOA",
    78: "Dialed Number NOA",
    79: "Ingress Codec Type",
    80: "Egress Codec Type",
    81: "Ingress RTP Packetization Time",
    82: "SBC Call ID",
    83: "Originator Echo Cancellation",
    84: "Terminator Echo Cancellation",
    85: "Charge Flag",
    86: "AMA Service Logic Identification",
    87: "AMA BAF Module",
    88: "AMA Set Hex AB Indication",
    89: "Service Feature ID",
    90: "FE Parameter",
    91: "Satellite Indicator",
    92: "PSX Billing Information",
    93: "Originating TDM Trunk Group Type",
    94: "Terminating TDM Trunk Group Type",
    95: "Ingress Trunk Member Number",
    96: "Egress Trunk Group ID",
    97: "Egress Switch ID",
    98: "Ingress Local ATM Address",
    99: "Ingress Remote ATM Address",
    100: "Egress Local ATM Address",
    101: "Egress Remote ATM Address",
    102: "Policy Response Call Type",
    103: "Outgoing Route Identification",
    104: "Outgoing Message Identification",
    105: "Incoming Route Identification",
    106: "Calling Name",
    107: "Calling Name Type",
    108: "Incoming Calling Party Numbering Plan",
    109: "Outgoing Calling Party Numbering Plan",
    110: "Calling Party Business Group ID",
    111: "Called Party Business Group ID",
    112: "Calling Party Public Presence Directory Number",
    113: "Elapsed Time from Receipt of Setup Message to Last Call Routing Attempt",
    114: "Billing Number NOA",
    115: "Incoming Calling Number NOA",
    116: "Egress Trunk Member Number",
    117: "Selected Route Type",
    118: "Telcordia Long Duration Record Type",
    119: "Time Elapsed from Previous Record",
    120: "Cumulative Route Index",
    121: "Call Disconnect Reason Transmitted to Ingress",
    122: "Call Disconnect Reason Transmitted to Egress",
    123: "ISDN PRI Calling Party Subaddress",
    124: "Outgoing Trunk Group Number in EXM",
    125: "Ingress Local Gateway Signaling IP Address",
    126: "Ingress Remote Gateway Signaling IP Address",
    127: "Record Sequence Number",
    128: "Transmission Medium Requirement (TMR)",
    129: "Information Transfer Rate (ITR)",
    130: "User Service Information (USI) User Information Layer 1",
    131: "Unrecognized Raw ISUP Calling Party Category",
    132: "Egress RLT Feature Specific Data",
    133: "Two B-Channel Transfer Feature Specific Data",
    134: "Calling Party Business Unit",
    135: "Called Party Business Unit",
    136: "Redirection Feature Specific Data",
    137: "Ingress RLT Feature Specific Data",
    138: "PSX Index",
    139: "PSX Congestion Level",
    140: "PSX Processing Time",
    141: "Script Name",
    142: "Ingress External Accounting Data",
    143: "Egress External Accounting Data",
    144: "Egress RTP Packetization Time",
    145: "Egress Number of Audio Bytes Sent",
    146: "Egress Number of Audio Packets Sent",
    147: "Egress Number of Audio Bytes Received",
    148: "Egress Number of Audio Packets Received",
    149: "Egress Number of Packets Recorded as Lost",
    150: "Egress Interarrival Packet Jitter",
    151: "Egress Last Measurement for Latency",
    152: "Ingress Maximum Packet Outage",
    153: "Egress Maximum Packet Outage",
    154: "Ingress Packet Playout Buffer Quality",
    155: "Egress Packet Playout Buffer Quality",
    156: "Answer Supervision Type",
    157: "Ingress SIP REFER and Replaces Feature Specific Data",
    158: "Egress SIP REFER and Replaces Feature Specific Data",
    159: "Network Transfer Feature Specific Data",
    160: "Call Condition",
    161: "Toll Indicator",
    162: "Generic Number (Number)",
    163: "Generic Number (Presentation Restriction Indicator)",
    164: "Generic Number (Numbering Plan)",
    165: "Generic Number (Nature of Address)",
    166: "Generic Number (Type)",
    167: "Originating Trunk Type",
    168: "Terminating Trunk Type",
    169: "Remote SBC Billing Indicator",
    170: "VPN Calling Private Presence Number",
    171: "VPN Calling Public Presence Number",
    172: "External Furnish Charging Info",
    173: "Ingress Policing Discards",
    174: "Egress Policing Discards",
    175: "Announcement ID",
    176: "Source Information",
    177: "Partition ID",
    178: "Network ID",
    179: "NCOS",
    180: "Ingress SRTP",
    181: "Egress SRTP",
    182: "ISDN Access Indicator from the Forward Call Indicator",
    183: "Call Disconnect Location",
    184: "Call Disconnect Location Transmitted to Ingress",
    185: "Call Disconnect Location Transmitted to Egress",
    186: "Network Call Reference - Call Identity",
    187: "Network Call Reference - Signaling Point Code",
    188: "Ingress ISUP MIME Protocol Variant Specific Data",
    189: "Egress ISUP MIME Protocol Variant Specific Data",
    190: "Modem Tone Type",
    191: "Modem Tone Signal Level",
    192: "Video Codec Data",
    193: "Video Codec Statistics",
    194: "SVS Customer",
    195: "SVS Vendor (deprecated)",
    196: "Call to Test PSX",
    197: "PSX Overlap Route Requests",
    198: "Call Setup Delay",
    199: "Overload Status",
    200: "RESERVED (Ingress Bicc Info)",
    201: "RESERVED (Egress Bicc Info)",
    202: "Ingress DSP Data",
    203: "Egress DSP Data",
    204: "Call Recorded Indicator",
    205: "Call Recorded RTP Tx IP Address",
    206: "Call Recorded RTP Tx Port Number",
    207: "Call Recorded RTP Rv IP Address",
    208: "Call Recorded RTP Rv Port Number",
    209: "MLPP Precedence Level",
    210: "RESERVED (MSRP Service Type)",
    211: "RESERVED (NPUKK Special Routing Information)",
    212: "RESERVED (NPUKK Customer Or Carrier Identification)",
    213: "RESERVED (NPUKK ServiceType Identifier)",
    214: "RESERVED (NPSSP Special Handling Information)",
    215: "RESERVED (NPSSP Service Type Identifier)",
    216: "RESERVED (Total ITX Charge Units)",
    217: "Global Charge Reference (GCR)",
    218: "RESERVED (IP Call Limit at ingress SIP Peer)",
    219: "RESERVED (IP Call Limit at ingress IPTG)",
    220: "RESERVED (IP BW Limit at ingress IPTG)",
    221: "RESERVED (IP Call Limit at egress SIP Peer)",
    222: "RESERVED (IP Call Limit at egress IPTG)",
    223: "RESERVED (IP BW Limit at egress IPTG)",
    224: "RESERVED (PSX Name)",
    225: "RESERVED (No. of PSX tried)",
    226: "Ingress Inbound R-Factor",
    227: "Ingress Outbound R-Factor",
    228: "Egress Inbound R-Factor",
    229: "Egress Outbound R-Factor",
    230: "Media Stream Data",
    231: "Media Stream Stats",
    232: "Transcode Indicator",
    233: "HD Codec Rate",
    234: "Remote Ingress Audio RTCP Learned Metrics",
    235: "Remote Egress Audio RTCP Learned Metrics",
    236: "Final Route Label",
    237: "MTA Information",
    238: "VBR Common Billing Data",
    239: "VBR Route Billing Data",
    240: "Access Transfer Specific Data",
    241: "Emergency Indicator",
    242: "Ingress Dtls-Srtp: Dtls-Srtp status info",
    243: "Egress Dtls-Srtp: Dtls-Srtp status info",
    244: "UE Roaming Status",
    245: "Access Network Charging Information",
    246: "Ingress Signaled Session Bandwidth in kbps",
    247: "Ingress Rx Computed Session Bandwidth in kbps",
    248: "Ingress Tx Computed Session Bandwidth in kbps",
    249: "Ingress Configured Bandwidth Reduction Factor",
    250: "Ingress Estimated Bandwidth Reduction Factor",
    251: "Egress Signaled Session Bandwidth in kbps",
    252: "Egress Rx Computed Session Bandwidth in kbps",
    253: "Egress Tx Computed Session Bandwidth in kbps",
    254: "Egress Configured Bandwidth Reduction Factor",
    255: "Egress Estimated Bandwidth Reduction Factor",
    256: "Additional Media Stream Statistics",
    257: "Ingress Zone Name",
    258: "Egress Zone Name",
    259: "Ingress Zone Id",
    260: "Egress Zone Id",
    261: "Video Cac",
    262: "Ingress IP Prefix Found TG Name",
    263: "Transcode Resource Type",
    264: "MRF Information",
    265: "Forking Call Parent GCID",
    266: "Call Recorder 1 RTP Tx Ip address",
    267: "Call Recorder 1 RTP Tx Port Number",
    268: "Call Recorder 1 RTP Rx IP address",
    269: "Call Recorder 1 RTP Rx Port Number",
    270: "Call Recorder 2 RTP Tx Ip address",
    271: "Call Recorder 2 RTP Tx Port Number",
    272: "Call Recorder 2 RTP Rx IP address",
    273: "Call Recorder 2 RTP Rx Port Number",
    274: "Call Recorder 3 RTP Tx Ip address",
    275: "Call Recorder 3 RTP Tx Port Number",
    276: "Call Recorder 3 RTP Rx IP address",
    277: "Call Recorder 3 RTP Rx Port Number",
    278: "SO-SBC",
    279: "Audio Stream Statistics",
    280: "Audio Stream RTCP-XR Voice Metric Statistics",
    281: "Media Stream SRTP Statistics",
    282: "DSP insertion/rejection reason",
    283: "Call Established Time",
    284: "Over Flow Packets Count",
    285: "Ingress Trunk Group for PSX Routing",
    286: "T140 Information",
    287: "Remote T140 RTCP Learned Metrics",
    288: "VTP Information",
    289: "Beep Tone Inserted",
    290: "Direction of Beep Tone",
    291: "Start Time (Local)",
    292: "Disconnect Time (Local)",
    293: "Call Established Time (Local)",
    294: "GUID",
    295: "Media IPSec Information",
    296: "Node Name",
    297: "Pod Name",
    298: "Container ID",
    299: "Ingress Identity Headers Received",
    300: "Egress Identity Headers Sent",
    301: "Minimum Recording Sessions",
},
    "ATTEMPT": {
        1: "Record Type",
        2: "Gateway Name",
        3: "Accounting ID",
        4: "Start Time in System Ticks",
        5: "Node Time Zone",
        6: "Start Time (Date)",
        7: "Start Time (Time)",
        8: "Time Elapsed from Receipt of Setup Message to Policy Server/SoftSwitch Response",
        9: "Time Elapsed from Receipt of Setup Message to Receipt of Alerting/ProcProg",
        10: "Disconnect Time (Time)",
        11: "Time Elapsed from Receipt of Disconnect to Completion of Call",
        12: "Call Disconnect Reason",
        13: "Service Delivered",
        14: "Call Direction",
        15: "Service Provider",
        16: "Transit Network Selection Code",
        17: "Calling Number",
        18: "Called Number",
        19: "Extra Called Address Digits",
        20: "Number of Called Num Translations Done by This Node",
        21: "Called Number Before Translation #1",
        22: "Translation Type 1",
        23: "Called Number Before Translation #2",
        24: "Translation Type 2",
        25: "Billing Number",
        26: "Route Label",
        27: "Route Attempt Number",
        28: "Route Selected",
        29: "Egress Local Gateway Signaling IP Address",
        30: "Egress Remote Gateway Signaling IP Address",
        31: "Ingress Trunk Group Name",
        32: "Ingress PSTN Circuit End Point",
        33: "Ingress IP Circuit End Point",
        34: "Egress PSTN Circuit End Point",
        35: "Egress IP Circuit End Point",
        36: "Originating Line Information (OLIP)",
        37: "Jurisdiction Information Parameter",
        38: "Carrier Code",
        39: "Call Group ID",
        40: "Script Log Data",
        41: "Time Elapsed from Receipt of Setup Message to Receipt of Exit Message",
        42: "Time Elapsed from Receipt of Setup Message to Generation of Exit Message",
        43: "Calling Party Nature of Address",
        44: "Called Party Nature of Address",
        45: "Ingress Protocol Variant Specific Data",
        46: "Ingress Signaling Type",
        47: "Egress Signaling Type",
        48: "Ingress Far End Switch Type",
        49: "Egress Far End Switch Type",
        50: "Far End Ingress TG Carrier Code",
        51: "Far End Egress TG Carrier Code",
        52: "Calling Party Category",
        53: "Dialed Number",
        54: "Carrier Selection Information",
        55: "Called Number Numbering Plan",
        56: "Generic Address Parameter",
        57: "Disconnect Initiator",
        58: "Egress Trunk Group Name",
        59: "Egress Protocol Variant Specific Data",
        60: "Incoming Calling Number",
        61: "AMA Call Type",
        62: "Message Billing Index (MBI)",
        63: "Originating LATA",
        64: "Route Index Used",
        65: "Calling Party Number Presentation Restriction",
        66: "Incoming ISUP Charge Number",
        67: "Incoming ISUP Charge Number NOA",
        68: "Dialed Number NOA",
        69: "Ingress Codec Type",
        70: "Egress Codec Type",
        71: "Ingress RTP Packetization Time",
        72: "SBC Call ID",
        73: "Terminated with Script Execution",
        74: "Originator Echo Cancellation",
        75: "Terminator Echo Cancellation",
        76: "Charge Flag",
        77: "AMA Service Logic Identification",
        78: "AMA BAF Module",
        79: "AMA Set Hex AB Indication",
        80: "Service Feature ID",
        81: "FE Parameter",
        82: "Satellite Indicator",
        83: "PSX Billing Information",
        84: "Originating TDM Trunk Group Type",
        85: "Terminating TDM Trunk Group Type",
        86: "Ingress Trunk Member Number",
        87: "Egress Trunk Group ID",
        88: "Egress Switch ID",
        89: "Ingress Local ATM Address",
        90: "Ingress Remote ATM Address",
        91: "Egress Local ATM Address",
        92: "Egress Remote ATM Address",
        93: "Policy Response Call Type",
        94: "Outgoing Route Identification",
        95: "Outgoing Message Identification",
        96: "Incoming Route Identification",
        97: "Calling Name",
        98: "Calling Name Type",
        99: "Incoming Calling Party Numbering Plan",
        100: "Outgoing Calling Party Numbering Plan",
        101: "Calling Party Business Group ID",
        102: "Called Party Business Group ID",
        103: "Calling Party Public Presence Directory Number",
        104: "Elapsed Time from Receipt of Setup Message to Last Call Routing Attempt",
        105: "Disconnect Time (Date)",
        106: "Billing Number NOA",
        107: "Incoming Calling Number NOA",
        108: "Egress Trunk Member Number",
        109: "Selected Route Type",
        110: "Cumulative Route Index",
        111: "Call Disconnect Reason Transmitted to Ingress",
        112: "Call Disconnect Reason Transmitted to Egress",
        113: "ISDN PRI Calling Party Subaddress",
        114: "Outgoing Trunk Group Number in EXM",
        115: "Ingress Local Gateway Signaling IP Address",
        116: "Ingress Remote Gateway Signaling IP Address",
        117: "Record Sequence Number",
        118: "Transmission Medium Requirement (TMR)",
        119: "Information Transfer Rate (ITR)",
        120: "User Service Information (USI) User Information Layer 1",
        121: "Unrecognized Raw ISUP Calling Party Category",
        122: "Egress RLT Feature Specific Data",
        123: "Two B-Channel Transfer Feature Specific Data",
        124: "Calling Party Business Unit",
        125: "Called Party Business Unit",
        126: "Redirection Feature Specific Data",
        127: "Ingress RLT Feature Specific Data",
        128: "PSX Index",
        129: "PSX Congestion Level",
        130: "PSX Processing Time",
        131: "Script Name",
        132: "Ingress External Accounting Data",
        133: "Egress External Accounting Data",
        134: "Egress RTP Packetization Time",
        135: "Answer Supervision Type",
        136: "Ingress SIP REFER and Replaces Feature Specific Data",
        137: "Egress SIP REFER and Replaces Feature Specific Data",
        138: "Network Transfer Feature Specific Data",
        139: "Call Condition",
        140: "Toll Indicator",
        141: "Generic Number (Number)",
        142: "Generic Number (Presentation Restriction Indicator)",
        143: "Generic Number (Numbering Plan)",
        144: "Generic Number (Nature of Address)",
        145: "Generic Number (Type)",
        146: "Final ATTEMPT Indicator",
        147: "Originating Trunk Type",
        148: "Terminating Trunk Type",
        149: "Remote SBC Billing Indicator",
        150: "Extra Disconnect Reason",
        151: "VPN Calling Private Presence Number",
        152: "VPN Calling Public Presence Number",
        153: "External Furnish Charging Info",
        154: "Announcement ID",
        155: "Source Information",
        156: "Partition ID",
        157: "Network ID",
        158: "NCOS",
        159: "ISDN Access Indicator from the Forward Call Indicator",
        160: "Call Disconnect Location",
        161: "Call Disconnect Location Transmitted to Ingress",
        162: "Call Disconnect Location Transmitted to Egress",
        163: "Network Call Reference - Call Identity",
        164: "Network Call Reference - Signaling Point Code",
        165: "Ingress ISUP MIME Protocol Variant Specific Data",
        166: "Egress ISUP MIME Protocol Variant Specific Data",
        167: "Video Codec Data Video Codec Statistics",
        168: "SVS Customer",
        169: "SVS Vendor (deprecated)",
        170: "Call to Test PSX",
        171: "PSX Overlap Route Requests",
        172: "Call Setup Delay",
        173: "Overload Status",
        174: "RESERVED (Ingress Bicc Info)",
        175: "RESERVED (Egress Bicc Info)",
        176: "MLPP Precedence Level",
        177: "RESERVED (MSRP Service Type)",
        178: "RESERVED (NPUKK Special Routing Information)",
        179: "RESERVED (NPUKK Customer Or Carrier Identification)",
        180: "RESERVED (NPUKK ServiceType Identifier)",
        181: "RESERVED (NPSSP Special Handling Information)",
        182: "RESERVED (NPSSP Service Type Identifier)",
        183: "RESERVED (ONI Str)",
        184: "RESERVED (Suppress ONI)",
        185: "Global Charge Reference (GCR)",
        186: "3xx Contact Information",
        187: "RESERVED (PSX Name)",
        188: "RESERVED (No. of PSX tried)",
        189: "Final Route Label",
        190: "MTA Information",
        191: "VBR Common Billing Data",
        192: "VBR Route Billing Data",
        193: "Access Transfer Specific Data",
        194: "Emergency Indicator",
        195: "UE Roaming Status",
        196: "Access Network Charging Information",
        197: "Ingress Zone Name",
        198: "Egress Zone Name",
        199: "Ingress Zone Id",
        200: "Egress Zone Id",
        201: "Ingress IP Prefix Found TG Name",
        202: "Additional Media Stream Statistics",
        203: "Forking Call Parent GCID",
        204: "SO-SBC",
        205: "DSP insertion/rejection reason",
        206: "Call Established Time",
        207: "Ingress Trunk Group for PSX Routing",
        208: "Start Time (Local)",
        209: "Disconnect Time (Local)",
        210: "Call Established Time (Local)",
        211: "GUID",
        212: "CAC Fail Info",
        213: "Node Name",
        214: "Pod Name",
        215: "Container ID",
        216: "Ingress Identity Headers Received",
        217: "Egress Identity Headers Sent",
    }
}

subfield_mappings = {
    "STOP": {
        52: ["Protocol Variant",
            "Call ID",
            "From Field",
            "To Field",
            "Redirect Attempt Count",
            "Reserved",
            "Display name of SIP URI PAI header",
            "User parameter of P-K-CallForwardingLast header",
            "Userinfo and Hostname of SIP request URI header",
            "Userinfo and Hostname of SIP URI PAI header",
            "Username parameter of the Proxy-Authorization header",
            "Displayname of Tel URI PAI header",
            "INVITE Contact header",
            "200 OK INVITE Contact header",
            "Redirecting Reason parameter of P-K CallForwardOriginal header",
            "Username of Tel URI PAI header",
            "Contractor number value",
            "ACK received for 200 OK",
            "Status Message For Call Release",
            "NAPT Status of the SIP Service Group for Signaling",
            "NAPT Status of the SIP Service Group for Media",
            "Original Peer SDP Address for NAPT or ICE",
            "UUI Sending Count",
            "UUI Receiving Count",
            "Service Information",
            "ICID",
            "Generated Host",
            "Originating IOI",
            "Terminating IOI",
            "Special Routing Table Number in the P-K-Adn Header",
            "IP Address for FQDN calls or IP address of route header selected as next hop",
            "Transport Protocol",
            "Direct Media Call",
            "Inbound SMM Indicator",
            "Outbound SMM Indicator",
            "Originating Charge Area",
            "Terminating Charge Area",
            "Feature Tag in Contact Header",
            "P-Charging-Function-Address",
            "P-Called-Party-Id",
            "P-Visited-Network-Id",
            "Direct Media with NAPT Call",
            "Ingress SMM Profile Name",
            "Egress SMM Profile Name",
            "P-Access-Network-Information header",
            "IMS Node functionality",
            "IMS node role",
            "IMS Use PcfaCcf",
            "P-CSCF calling party",
            "P-CSCF called party",
            "ICE used on Call",
            "ICE Complete",
            "Transit IOI List",
            "Loop Back Ravel Call",
            "Optimal Media Routing Applied",
            "IMS PAI Service header",
            "Feature-Caps header",
            "Called Asserted Identity",
            "NNI-Type",
            "Neighbour Address",
            "Relationship mode",
            "Session direction",
            "SMM CDR Field #1",
            "SMM CDR Field #2",
            "SMM CDR Field #3",
            "SMM CDR Field #4",
            "SMM CDR Field #5",
            "Origination ID",
            "STI Service Type",
            "STI Service Status",
            "STI Reason Code",
            "Ingress Global SMM Profile Name",
            "Egress Global SMM Profile Name",
            "Ingress AddrContext SMM Profile Name",
            "Egress AddrContext SMM Profile Name",
            "Ingress Zone SMM Profile Name",
            "Egress Zone SMM Profile Name",
            "STI Display Name",
            "AniDnis Loop Detection Fail",
            "P-K-Info \"No-Charge\" Indicator",
            "Attestation-Indicator",
            "STI RPH Service Type",
            "STI RPH Service Status",
            "STI RPH Reason Code",
            "STI RCD Service Type",
            "STI RCD Service Status",
            "STI RCD Reason Code",
            ],
        52.1: ["Protocol", "Gateway to Gateway handle"],
        69: ["Protocol Variant",
            "Call ID",
            "From Field",
            "To Field",
            "Redirect Attempt Count",
            "Reserved",
            "Display name of SIP URI PAI header",
            "User parameter of P-K-CallForwardingLast header",
            "Userinfo and Hostname of SIP request URI header",
            "Userinfo and Hostname of SIP URI PAI header",
            "Username parameter of the Proxy-Authorization header",
            "Displayname of Tel URI PAI header",
            "INVITE Contact header",
            "200 OK INVITE Contact header",
            "Redirecting Reason parameter of P-K CallForwardOriginal header",
            "Username of Tel URI PAI header",
            "Contractor number value",
            "ACK received for 200 OK",
            "Status Message For Call Release",
            "NAPT Status of the SIP Service Group for Signaling",
            "NAPT Status of the SIP Service Group for Media",
            "Original Peer SDP Address for NAPT or ICE",
            "UUI Sending Count",
            "UUI Receiving Count",
            "Service Information",
            "ICID",
            "Generated Host",
            "Originating IOI",
            "Terminating IOI",
            "Special Routing Table Number in the P-K-Adn Header",
            "IP Address for FQDN calls or IP address of route header selected as next hop",
            "Transport Protocol",
            "Direct Media Call",
            "Inbound SMM Indicator",
            "Outbound SMM Indicator",
            "Originating Charge Area",
            "Terminating Charge Area",
            "Feature Tag in Contact Header",
            "P-Charging-Function-Address",
            "P-Called-Party-Id",
            "P-Visited-Network-Id",
            "Direct Media with NAPT Call",
            "Ingress SMM Profile Name",
            "Egress SMM Profile Name",
            "P-Access-Network-Information header",
            "IMS Node functionality",
            "IMS node role",
            "IMS Use PcfaCcf",
            "P-CSCF calling party",
            "P-CSCF called party",
            "ICE used on Call",
            "ICE Complete",
            "Transit IOI List",
            "Loop Back Ravel Call",
            "Optimal Media Routing Applied",
            "IMS PAI Service header",
            "Feature-Caps header",
            "Called Asserted Identity",
            "NNI-Type",
            "Neighbour Address",
            "Relationship mode",
            "Session direction",
            "SMM CDR Field #1",
            "SMM CDR Field #2",
            "SMM CDR Field #3",
            "SMM CDR Field #4",
            "SMM CDR Field #5",
            "Origination ID",
            "STI Service Type",
            "STI Service Status",
            "STI Reason Code",
            "Ingress Global SMM Profile Name",
            "Egress Global SMM Profile Name",
            "Ingress AddrContext SMM Profile Name",
            "Egress AddrContext SMM Profile Name",
            "Ingress Zone SMM Profile Name",
            "Egress Zone SMM Profile Name",
            "STI Display Name",
            "AniDnis Loop Detection Fail",
            "P-K-Info \"No-Charge\" Indicator",
            "Attestation-Indicator",
            "STI RPH Service Type",
            "STI RPH Service Status",
            "STI RPH Reason Code",
            "STI RCD Service Type",
            "STI RCD Service Status",
            "STI RCD Reason Code",
            ],
        69.1: ["Protocol", "Gateway to Gateway handle"],
        198: ["Request Latency (msec)", "Downstream Latency (msec)", "Response Latency (msec)", "Upstream Latency (msec)"],
        230: ["Number of Streams",
            "mediaType1",
            "streamIndex1",
            "ingress codec used1",
            "ingress local IP1",
            "ingress remote IP1",
            "ingress SRTP Info1",
            "ingress bw1",
            "egress codec Used1",
            "egress local IP1",
            "egress remote IP1",
            "egress SRTP info1",
            "egress bw1",
            "ingress private leg local EP1",
            "ingress private leg remote EP1",
            "egress private leg local EP1",
            "egress private leg remote EP1",
            "mediaType2",
            "streamIndex2",
            "ingress codec used2",
            "ingress local IP2",
            "ingress remote IP2",
            "ingress SRTP info2",
            "ingress bw2",
            "egress codec used2",
            "egress local IP2",
            "egress remote IP2",
            "egress SRTP info2",
            "egress bw2",
            "ingress private leg local EP2",
            "ingress private leg remote EP2",
            "egress private leg local EP2",
            "egress private leg remote EP2",
            "mediaType3",
            "streamIndex3",
            "ingress codec used3",
            "ingress local IP3",
            "ingress remote IP3",
            "ingress SRTP info3",
            "ingress bw3",
            "egress codec used3",
            "egress local IP3",
            "egress remote IP3",
            "egress SRTP info3",
            "egress bw3",
            "ingress private leg local EP3",
            "ingress private leg remote EP3",
            "egress private leg local EP3",
            "egress private leg remote EP3",
            "mediaType4",
            "streamIndex4",
            "ingress codec used4",
            "ingress local IP4",
            "ingress remote IP4",
            "ingress SRTP info4",
            "ingress bw4",
            "egress codec used4",
            "egress local IP4",
            "egress remote IP4",
            "egress SRTP info4",
            "egress bw4",
            "ingress private leg local EP4",
            "ingress private leg remote EP4",
            "egress private leg local EP4",
            "egress private leg remote EP4",
            "mediaType5",
            "streamIndex5",
            "ingress codec used5",
            "ingress local IP5",
            "ingress remote IP5",
            "ingress SRTP info5",
            "ingress bw5",
            "egress codec used5",
            "egress local IP5",
            "egress remote IP5",
            "egress SRTP info5",
            "egress bw5",
            "ingress private leg local EP5",
            "ingress private leg remote EP5",
            "egress private leg local EP5",
            "egress private leg remote EP5",
            "mediaType6",
            "streamIndex6",
            "ingress codec used6",
            "ingress local IP6",
            "ingress remote IP6",
            "ingress SRTP info6",
            "ingress bw6",
            "egress codec used6",
            "egress local IP6",
            "egress remote IP6",
            "egress SRTP info6",
            "egress bw6",
            "ingress private leg local EP6",
            "ingress private leg remote EP6",
            "egress private leg local EP6",
            "egress private leg remote EP6",
        ],
        231: ["mediaType1",
            "streamIndex1",
            "ingress packetSent1",
            "ingress packetReceived1",
            "ingress octetSent1",
            "ingress octetReceived1",
            "ingress packetLost1",
            "ingress packetDiscarded1",
            "egress packetSent1",
            "egress packetReceived1",
            "egress octetSent1",
            "egress octetReceived1",
            "egress packetLost1",
            "egress packetDiscarded1",
            "mediaType2",
            "streamIndex2",
            "ingress packetSent2",
            "ingress packetReceived2",
            "ingress octetSent2",
            "ingress octetReceived2",
            "ingress packetLost2",
            "ingress packetDiscarded2",
            "egress packetSent2",
            "egress packetReceived2",
            "egress octetSent2",
            "egress octetReceived2",
            "egress packetLost2",
            "egress packetDiscarded2",
            "mediaType3",
            "streamIndex3",
            "ingress packetSent3",
            "ingress packetReceived3",
            "ingress octetSent3",
            "ingress octetReceived3",
            "ingress packetLost3",
            "ingress packetDiscarded3",
            "egress packetSent3",
            "egress packetReceived3",
            "egress octetSent3",
            "egress octetReceived3",
            "egress packetLost3",
            "egress packetDiscarded3",
            ],
        256: ["Entries per stream",
            "Number of streams",
            "ingress lostPktBursts1",
            "ingress lostPktSingles1",
            "ingress codecParams1",
            "egress lostPktBursts1",
            "egress lostPktSingles1",
            "egress codecParams1",
            "transcode indicator1",
            "ingress lostPktBursts2",
            "ingress lostPktSingles2",
            "ingress codecParams2",
            "egress lostPktBursts2",
            "egress lostPktSingles2",
            "egress codecParams2",
            "transcode indicator2",
            "ingress lostPktBursts3",
            "ingress lostPktSingles3",
            "ingress codecParams3",
            "egress lostPktBursts3",
            "egress lostPktSingles3",
            "egress codecParams3",
            "transcode indicator3",
            "ingress lostPktBursts4",
            "ingress lostPktSingles4",
            "ingress codecParams4",
            "egress lostPktBursts4",
            "egress lostPktSingles4",
            "egress codecParams4",
            "transcode indicator4",
            "ingress lostPktBursts5",
            "ingress lostPktSingles5",
            "ingress codecParams5",
            "egress lostPktBursts5",
            "egress lostPktSingles5",
            "egress codecParams5",
            "transcode indicator5",
            "ingress lostPktBursts6",
            "ingress lostPktSingles6",
            "ingress codecParams6",
            "egress lostPktBursts6",
            "egress lostPktSingles6",
            "egress codecParams6",
            "transcode indicator6",
        ],
        281: ["Entries per stream",
            "Number of streams",
            "ingress authFailureCount1",
            "ingress outsideReplayCount1",
            "egress authFailureCount1",
            "egress outsideReplayCount1",
            "ingress authFailureCount2",
            "ingress outsideReplayCount2",
            "egress authFailureCount2",
            "egress outsideReplayCount2",
            "ingress authFailureCount3",
            "ingress outsideReplayCount3",
            "egress authFailureCount3",
            "egress outsideReplayCount3",
            "ingress authFailureCount4",
            "ingress outsideReplayCount4",
            "egress authFailureCount4",
            "egress outsideReplayCount4",
            "ingress authFailureCount5",
            "ingress outsideReplayCount5",
            "egress authFailureCount5",
            "egress outsideReplayCount5",
            "ingress authFailureCount6",
            "ingress outsideReplayCount6",
            "egress authFailureCount6",
            "egress outsideReplayCount6",
        ],
        282: ["Entries per stream", "Number of streams", "ingress dspReason1", "egress dspReason1"],
        284: ["ingress overFlowPacketsCount1", "egress overFlowPacketsCount1"],
        295: ["IPSec Enabled", "Ingress Remote Tunnel IP", "Egress Remote Tunnel IP"]
    },
    "START": {
        42: ["Protocol Variant",
            "Call ID",
            "From Field",
            "To Field",
            "Redirect Attempt Count",
            "Reserved",
            "Display name of SIP URI PAI header",
            "User parameter of P-K-CallForwardingLast header",
            "Userinfo and Hostname of SIP request URI header",
            "Userinfo and Hostname of SIP URI PAI header",
            "Username parameter of the Proxy-Authorization header",
            "Displayname of Tel URI PAI header",
            "INVITE Contact header",
            "200 OK INVITE Contact header",
            "Redirecting Reason parameter of P-K CallForwardOriginal header",
            "Username of Tel URI PAI header",
            "Contractor number value",
            "ACK received for 200 OK",
            "Status Message For Call Release",
            "NAPT Status of the SIP Service Group for Signaling",
            "NAPT Status of the SIP Service Group for Media",
            "Original Peer SDP Address for NAPT or ICE",
            "UUI Sending Count",
            "UUI Receiving Count",
            "Service Information",
            "ICID",
            "Generated Host",
            "Originating IOI",
            "Terminating IOI",
            "Special Routing Table Number in the P-K-Adn Header",
            "IP Address for FQDN calls or IP address of route header selected as next hop",
            "Transport Protocol",
            "Direct Media Call",
            "Inbound SMM Indicator",
            "Outbound SMM Indicator",
            "Originating Charge Area",
            "Terminating Charge Area",
            "Feature Tag in Contact Header",
            "P-Charging-Function-Address",
            "P-Called-Party-Id",
            "P-Visited-Network-Id",
            "Direct Media with NAPT Call",
            "Ingress SMM Profile Name",
            "Egress SMM Profile Name",
            "P-Access-Network-Information header",
            "IMS Node functionality",
            "IMS node role",
            "IMS Use PcfaCcf",
            "P-CSCF calling party",
            "P-CSCF called party",
            "ICE used on Call",
            "ICE Complete",
            "Transit IOI List",
            "Loop Back Ravel Call",
            "Optimal Media Routing Applied",
            "IMS PAI Service header",
            "Feature-Caps header",
            "Called Asserted Identity",
            "NNI-Type",
            "Neighbour Address",
            "Relationship mode",
            "Session direction",
            "SMM CDR Field #1",
            "SMM CDR Field #2",
            "SMM CDR Field #3",
            "SMM CDR Field #4",
            "SMM CDR Field #5",
            "Origination ID",
            "STI Service Type",
            "STI Service Status",
            "STI Reason Code",
            "Ingress Global SMM Profile Name",
            "Egress Global SMM Profile Name",
            "Ingress AddrContext SMM Profile Name",
            "Egress AddrContext SMM Profile Name",
            "Ingress Zone SMM Profile Name",
            "Egress Zone SMM Profile Name",
            "STI Display Name",
            "AniDnis Loop Detection Fail",
            "P-K-Info \"No-Charge\" Indicator",
            "Attestation-Indicator",
            "STI RPH Service Type",
            "STI RPH Service Status",
            "STI RPH Reason Code",
            "STI RCD Service Type",
            "STI RCD Service Status",
            "STI RCD Reason Code",
            ],
        42.1: ["Protocol", "Gateway to Gateway handle"],
        55: ["Protocol Variant",
            "Call ID",
            "From Field",
            "To Field",
            "Redirect Attempt Count",
            "Reserved",
            "Display name of SIP URI PAI header",
            "User parameter of P-K-CallForwardingLast header",
            "Userinfo and Hostname of SIP request URI header",
            "Userinfo and Hostname of SIP URI PAI header",
            "Username parameter of the Proxy-Authorization header",
            "Displayname of Tel URI PAI header",
            "INVITE Contact header",
            "200 OK INVITE Contact header",
            "Redirecting Reason parameter of P-K CallForwardOriginal header",
            "Username of Tel URI PAI header",
            "Contractor number value",
            "ACK received for 200 OK",
            "Status Message For Call Release",
            "NAPT Status of the SIP Service Group for Signaling",
            "NAPT Status of the SIP Service Group for Media",
            "Original Peer SDP Address for NAPT or ICE",
            "UUI Sending Count",
            "UUI Receiving Count",
            "Service Information",
            "ICID",
            "Generated Host",
            "Originating IOI",
            "Terminating IOI",
            "Special Routing Table Number in the P-K-Adn Header",
            "IP Address for FQDN calls or IP address of route header selected as next hop",
            "Transport Protocol",
            "Direct Media Call",
            "Inbound SMM Indicator",
            "Outbound SMM Indicator",
            "Originating Charge Area",
            "Terminating Charge Area",
            "Feature Tag in Contact Header",
            "P-Charging-Function-Address",
            "P-Called-Party-Id",
            "P-Visited-Network-Id",
            "Direct Media with NAPT Call",
            "Ingress SMM Profile Name",
            "Egress SMM Profile Name",
            "P-Access-Network-Information header",
            "IMS Node functionality",
            "IMS node role",
            "IMS Use PcfaCcf",
            "P-CSCF calling party",
            "P-CSCF called party",
            "ICE used on Call",
            "ICE Complete",
            "Transit IOI List",
            "Loop Back Ravel Call",
            "Optimal Media Routing Applied",
            "IMS PAI Service header",
            "Feature-Caps header",
            "Called Asserted Identity",
            "NNI-Type",
            "Neighbour Address",
            "Relationship mode",
            "Session direction",
            "SMM CDR Field #1",
            "SMM CDR Field #2",
            "SMM CDR Field #3",
            "SMM CDR Field #4",
            "SMM CDR Field #5",
            "Origination ID",
            "STI Service Type",
            "STI Service Status",
            "STI Reason Code",
            "Ingress Global SMM Profile Name",
            "Egress Global SMM Profile Name",
            "Ingress AddrContext SMM Profile Name",
            "Egress AddrContext SMM Profile Name",
            "Ingress Zone SMM Profile Name",
            "Egress Zone SMM Profile Name",
            "STI Display Name",
            "AniDnis Loop Detection Fail",
            "P-K-Info \"No-Charge\" Indicator",
            "Attestation-Indicator",
            "STI RPH Service Type",
            "STI RPH Service Status",
            "STI RPH Reason Code",
            "STI RCD Service Type",
            "STI RCD Service Status",
            "STI RCD Reason Code",
            ],
        55.1: ["Protocol", "Gateway to Gateway handle"],
        153: ["Request Latency (msec)", "Downstream Latency (msec)", "Response Latency (msec)", "Upstream Latency (msec)"]    
    },
    "ATTEMPT": {
        45: ["Protocol Variant",
            "Call ID",
            "From Field",
            "To Field",
            "Redirect Attempt Count",
            "Reserved",
            "Display name of SIP URI PAI header",
            "User parameter of P-K-CallForwardingLast header",
            "Userinfo and Hostname of SIP request URI header",
            "Userinfo and Hostname of SIP URI PAI header",
            "Username parameter of the Proxy-Authorization header",
            "Displayname of Tel URI PAI header",
            "INVITE Contact header",
            "200 OK INVITE Contact header",
            "Redirecting Reason parameter of P-K CallForwardOriginal header",
            "Username of Tel URI PAI header",
            "Contractor number value",
            "ACK received for 200 OK",
            "Status Message For Call Release",
            "NAPT Status of the SIP Service Group for Signaling",
            "NAPT Status of the SIP Service Group for Media",
            "Original Peer SDP Address for NAPT or ICE",
            "UUI Sending Count",
            "UUI Receiving Count",
            "Service Information",
            "ICID",
            "Generated Host",
            "Originating IOI",
            "Terminating IOI",
            "Special Routing Table Number in the P-K-Adn Header",
            "IP Address for FQDN calls or IP address of route header selected as next hop",
            "Transport Protocol",
            "Direct Media Call",
            "Inbound SMM Indicator",
            "Outbound SMM Indicator",
            "Originating Charge Area",
            "Terminating Charge Area",
            "Feature Tag in Contact Header",
            "P-Charging-Function-Address",
            "P-Called-Party-Id",
            "P-Visited-Network-Id",
            "Direct Media with NAPT Call",
            "Ingress SMM Profile Name",
            "Egress SMM Profile Name",
            "P-Access-Network-Information header",
            "IMS Node functionality",
            "IMS node role",
            "IMS Use PcfaCcf",
            "P-CSCF calling party",
            "P-CSCF called party",
            "ICE used on Call",
            "ICE Complete",
            "Transit IOI List",
            "Loop Back Ravel Call",
            "Optimal Media Routing Applied",
            "IMS PAI Service header",
            "Feature-Caps header",
            "Called Asserted Identity",
            "NNI-Type",
            "Neighbour Address",
            "Relationship mode",
            "Session direction",
            "SMM CDR Field #1",
            "SMM CDR Field #2",
            "SMM CDR Field #3",
            "SMM CDR Field #4",
            "SMM CDR Field #5",
            "Origination ID",
            "STI Service Type",
            "STI Service Status",
            "STI Reason Code",
            "Ingress Global SMM Profile Name",
            "Egress Global SMM Profile Name",
            "Ingress AddrContext SMM Profile Name",
            "Egress AddrContext SMM Profile Name",
            "Ingress Zone SMM Profile Name",
            "Egress Zone SMM Profile Name",
            "STI Display Name",
            "AniDnis Loop Detection Fail",
            "P-K-Info \"No-Charge\" Indicator",
            "Attestation-Indicator",
            "STI RPH Service Type",
            "STI RPH Service Status",
            "STI RPH Reason Code",
            "STI RCD Service Type",
            "STI RCD Service Status",
            "STI RCD Reason Code",
            ],
        45.1: ["Protocol", "Gateway to Gateway handle"],
        59: ["Protocol Variant",
            "Call ID",
            "From Field",
            "To Field",
            "Redirect Attempt Count",
            "Reserved",
            "Display name of SIP URI PAI header",
            "User parameter of P-K-CallForwardingLast header",
            "Userinfo and Hostname of SIP request URI header",
            "Userinfo and Hostname of SIP URI PAI header",
            "Username parameter of the Proxy-Authorization header",
            "Displayname of Tel URI PAI header",
            "INVITE Contact header",
            "200 OK INVITE Contact header",
            "Redirecting Reason parameter of P-K CallForwardOriginal header",
            "Username of Tel URI PAI header",
            "Contractor number value",
            "ACK received for 200 OK",
            "Status Message For Call Release",
            "NAPT Status of the SIP Service Group for Signaling",
            "NAPT Status of the SIP Service Group for Media",
            "Original Peer SDP Address for NAPT or ICE",
            "UUI Sending Count",
            "UUI Receiving Count",
            "Service Information",
            "ICID",
            "Generated Host",
            "Originating IOI",
            "Terminating IOI",
            "Special Routing Table Number in the P-K-Adn Header",
            "IP Address for FQDN calls or IP address of route header selected as next hop",
            "Transport Protocol",
            "Direct Media Call",
            "Inbound SMM Indicator",
            "Outbound SMM Indicator",
            "Originating Charge Area",
            "Terminating Charge Area",
            "Feature Tag in Contact Header",
            "P-Charging-Function-Address",
            "P-Called-Party-Id",
            "P-Visited-Network-Id",
            "Direct Media with NAPT Call",
            "Ingress SMM Profile Name",
            "Egress SMM Profile Name",
            "P-Access-Network-Information header",
            "IMS Node functionality",
            "IMS node role",
            "IMS Use PcfaCcf",
            "P-CSCF calling party",
            "P-CSCF called party",
            "ICE used on Call",
            "ICE Complete",
            "Transit IOI List",
            "Loop Back Ravel Call",
            "Optimal Media Routing Applied",
            "IMS PAI Service header",
            "Feature-Caps header",
            "Called Asserted Identity",
            "NNI-Type",
            "Neighbour Address",
            "Relationship mode",
            "Session direction",
            "SMM CDR Field #1",
            "SMM CDR Field #2",
            "SMM CDR Field #3",
            "SMM CDR Field #4",
            "SMM CDR Field #5",
            "Origination ID",
            "STI Service Type",
            "STI Service Status",
            "STI Reason Code",
            "Ingress Global SMM Profile Name",
            "Egress Global SMM Profile Name",
            "Ingress AddrContext SMM Profile Name",
            "Egress AddrContext SMM Profile Name",
            "Ingress Zone SMM Profile Name",
            "Egress Zone SMM Profile Name",
            "STI Display Name",
            "AniDnis Loop Detection Fail",
            "P-K-Info \"No-Charge\" Indicator",
            "Attestation-Indicator",
            "STI RPH Service Type",
            "STI RPH Service Status",
            "STI RPH Reason Code",
            "STI RCD Service Type",
            "STI RCD Service Status",
            "STI RCD Reason Code",
            ],
        59.1: ["Protocol", "Gateway to Gateway handle"],
        172: ["Request Latency (msec)", "Downstream Latency (msec)", "Response Latency (msec)", "Upstream Latency (msec)"],
        205: ["Entries per stream", "Number of streams", "ingress dspReason1", "egress dspReason1"],
        212: ["CAC Level", "CAC Type", "Cause Text", "Q850 Code"]
    }
}

cdr_disconnect_reason = {
    "DR0": "INVALID DISCONNECT REASON",
    "DR1": "UNALLOCATED NUMBER",
    "DR2": "NO ROUTE TO SPECIFIED NETWORK",
    "DR3": "NO ROUTE TO DESTINATION",
    "DR4": "SEND SPECIAL INFO TONE",
    "DR5": "MISDIALED TRUNK PREFIX",
    "DR6": "CHANNEL UNACCEPTABLE",
    "DR7": "CALL AWARDED",
    "DR8": "PREEMPTION",
    "DR9": "PREEMPTION - CIRCUIT RESERVED",
    "DR12": "VALUE NOT CODED",
    "DR16": "NORMAL ROUTE CLEARING",
    "DR17": "USER BUSY",
    "DR18": "NO USER RESPONDING",
    "DR19": "NO ANSWER FROM USER",
    "DR20": "SUBSCRIBER ABSENT",
    "DR21": "CALL REJECTED",
    "DR22": "NUMBER CHANGED",
    "DR23": "UNALLOCATED DESTINATION NUMBER",
    "DR24": "UNKNOWN BUSINESS GROUP",
    "DR25": "EXCHANGE ROUTING ERROR",
    "DR26": "MISROUTED CALL TO PORTED NUMBER",
    "DR27": "DESTINATION OUT OF ORDER",
    "DR28": "INVALID NUMBER FORMAT",
    "DR29": "FACILITY REJECTED",
    "DR30": "RESPONSE TO STATUS ENQUIRY",
    "DR31": "NORMAL UNSPECIFIED",
    "DR32": "VALUE NOT CODED",
    "DR34": "NO CIRCUIT AVAILABLE",
    "DR35": "VALUE NOT CODED",
    "DR36": "VALUE NOT CODED",
    "DR38": "NETWORK OUT OF ORDER",
    "DR39": "PERM FM CONNECTION OOS",
    "DR40": "PERM FM CONNECTION OPERATIONAL",
    "DR41": "TEMPORARY FAILURE",
    "DR42": "SWITCHING EQUIPMENT CONGESTION",
    "DR43": "ACCESS INFORMATION DISCARDED",
    "DR44": "REQUESTED CIRCUIT NOT AVAILABLE",
    "DR45": "ANSI PREEMPTION",
    "DR46": "PRECEDENCE CALL BLOCKED",
    "DR47": "RESOURCE UNAVAILABLE UNSPECIFIED",
    "DR49": "QUALITY OF SERVICE UNAVAILABLE",
    "DR50": "REQUESTED FACILITY NOT SUBSCRIBED",
    "DR51": "CALL TYPE INCOMPATIBLE WITH SERVICE",
    "DR53": "OUTGOING CALL BARRED CUG",
    "DR54": "CALL BLOCKED GROUP RESTRICTIONS",
    "DR55": "INCOMING CALL BARRED CUG",
    "DR57": "BEARER CAPABILITY NOT AUTHORIZED",
    "DR58": "BEARER CAPABILITY PRESENTLY NOT AVAILABLE",
    "DR62": "INCONSISTENT OUTGOING SUBSCRIBER CLASS",
    "DR63": "SERVICE OR OPTION NOT AVAILABLE UNSPECIFIED",
    "DR65": "BEARER CAPABILITY NOT IMPLEMENTED",
    "DR66": "CHANNEL TYPE NOT IMPLEMENTED",
    "DR69": "REQUESTED FACILITY NOT IMPLEMENTED",
    "DR70": "ONLY RESTRICTED DIGITAL INFO BEARER CAPABILITY AVAILABLE",
    "DR79": "SERVICE OR OPTION NOT IMPLEMENTED UNSPECIFIED",
    "DR80": "VALUE NOT CODED",
    "DR81": "INVALID CALL REFERENCE",
    "DR82": "CHANNEL DOES NOT EXIST",
    "DR83": "SUSPENDED CALL NO IDENTITY",
    "DR84": "CALL IDENTITY IN USE",
    "DR85": "NO CALL SUSPENDED",
    "DR86": "CALL IDENTITY CLEARED",
    "DR87": "NOT MEMBER OF CUG",
    "DR88": "INCOMPATIBLE DESTINATION",
    "DR90": "NON-EXISTENT CUG",
    "DR91": "INVALID NETWORK SELECTION",
    "DR95": "INVALID MESSAGE UNSPECIFIED",
    "DR96": "MANDATORY INFORMATION ELEMENT MISSING",
    "DR97": "MESSAGE TYPE NON-EXISTENT OR NOT IMPLEMENTED",
    "DR98": "MSG TYPE NC NE OR NI",
    "DR99": "IE NOT IMPLEMENTED",
    "DR100": "INVALID INFORMATION ELEMENT CONTENT",
    "DR101": "MSG NOT COMPATIBLE WITH STATE",
    "DR102": "RECOVERY ON TIMER EXPIRY",
    "DR103": "PARAMETER NOT IMPLEMENTED",
    "DR110": "UNRECOGNIZED PARAMETER",
    "DR111": "PROTOCOL ERROR UNSPECIFIED",
    "DR127": "INTERWORKING UNSPECIFIED",
    "DR128": "RESOURCES ALLOCATION FAILURE",
    "DR129": "CHANNEL COLLISION BACKOFF",
    "DR130": "INSUFFICIENT DESTINATION RESOURCES",
    "DR131": "RESOURCE FAILURE",
    "DR132": "MODULE FAILURE",
    "DR133": "MEDIA GATEWAY SERVICE GROUP EGRESS DISCONNECT",
    "DR134": "CONTINUITY CHECK FAILED, BACKOFF",
    "DR135": "COLLISION REATTEMPT EXHAUSTED",
    "DR136": "CONTINUITY REATTEMPT EXHAUSTED",
    "DR137": "NO ROUTE FOR BEARER CAPABILITY",
    "DR138": "NO ROUTE SIGNALING",
    "DR139": "NO ROUTE DIRECTION",
    "DR140": "CIRCUIT ENDPOINT RESOURCE ALLOCATION FAILURE",
    "DR141": "DISCONNECT WITH NEW DESTINATION",
    "DR142": "AUTOMATIC CONGESTION CONTROL PROCEDURE",
    "DR143": "ACC ALTERNATE ROUTE",
    "DR144": "PACKET LOSS EXCEEDS THRESHOLD",
    "DR145": "NO RTP OR RTCP PACKETS",
    "DR146": "HOP COUNTER EXHAUSTED",
    "DR147": "CONVERSION FAILURE",
    "DR148": "CPC_DISC_CONGESTION_REROUTE_NOT_PERMITTED",
    "DR149": "CPC_DISC_SBC_INCOMPATIBLE_DESTINATION",
    "DR150": "CPC_DISC_NO_PSX_ROUTES",
    "DR151": "CPC_DISC_SETUP_REQ_TIMER_EXPIRY",
    "DR152": "CPC_DISC_GW_CONGESTED",
    "DR153": "CPC_DISC_GLARE_OCCURRED",
    "DR154": "CPC_DISC_NO_TERM_CIT_RCVD",
    "DR155": "CPC_DISC_BUSY_EVERYWHERE",
    "DR156": "CPC_DISC_REASON_UNKNOWN_RESOURCE_PRIORITY",
    "DR157": "CPC_DISC_REASON_BAD_EXTENSION",
    "DR158": "CPC_DISC_REASON_QUEUE_TIMEOUT",
    "DR159": "CPC_DISC_REASON_FORBIDDEN",
    "DR160": "RESERVED FOR FUTURE USE",
    "DR161": "CPC_DISC_REASON_QUEUEING_IMPOSSIBLE",
    "DR162": "CPC_DISC_ACC_INGRESS",
    "DR163": "CPC_DISC_UA_PREEMPTION",
    "DR164": "CPC_DISC_NETWORK_PREEMPTION",
    "DR165": "CPC_DISC_RESOURCE_LIST_TRANS_FAIL",
    "DR166": "CPC_DISC_PDD_TIMER_EXPIRED",
    "DR168": "CPC_DISC_REASON_ADDRESS_UNREACHABLE",
    "DR169": "CPC_DISC_REASON_ADDRESS_UNREACHABLE_ARS",
    "DR172": "CPC_DISC_ERROR_INFO_RLS",
    "DR176": "CPC_DISC_TG_AUTH_FAIL",
    "DR177": "CPC_DISC_TG_AUTH_FAIL_401_407",
    "DR178": "CPC_DISC_RX_RAR_GUARD_TIMER_EXPIRED",
    "DR179": "CPC_DISC_INFO_METHOD_REJECT",
    "DR180": "CPC_DISC_MESSAGE_METHOD_REJECT",
    "DR181": "CPC_DISC_NOTIFY_METHOD_REJECT",
    "DR182": "CPC_DISC_OPTIONS_METHOD_REJECT",
    "DR183": "CPC_DISC_PUBLISH_METHOD_REJECT",
    "DR184": "CPC_DISC_REFER_METHOD_REJECT",
    "DR185": "CPC_DISC_REGISTER_METHOD_REJECT",
    "DR186": "CPC_DISC_SUBSCRIBE_METHOD_REJECT",
    "DR187": "CPC_DISC_UPDATE_METHOD_REJECT",
    "DR188": "CPC_DISC_EP_CAC_VIDEO_THR",
    "DR189": "CPC_DISC_REFER_METHOD_RELAY",
    "DR190": "CPC_DISC_ENCRYPT_LICENSE_ENFORCED",
    "DR191": "CPC_DISC_SRTP_LICENSE_ENFORCED",
    "DR192": "CPC_DISC_RETRY_PROFILE_IN_REDIRECT_MODE",
    "DR193": "CPC_DISC_WITH_RETRY_PROFILE",
    "DR194": "CPC_DISC_AMRNB_LICENSE_ENFORCED",
    "DR195": "CPC_DISC_AMRWB_LICENSE_ENFORCED",
    "DR196": "CPC_DISC_EVRC_LICENSE_ENFORCED",
    "DR197": "CPC_DISC_MRF_CALL_CLEANUP_RCVD",
    "DR198": "CPC_DISC_MRF_MODIFY_FAILED",
    "DR199": "CPC_DISC_VDSP_LICENSE_ENFORCED",
    "DR200": "CPC_DISC_MRF_LICENSE_ENFORCED",
    "DR201": "CPC_DISC_CAC_NON_REG_LIMIT_REACHED",
    "DR202": "CPC_DISC_EVS_LICENSE_ENFORCED",
    "DR203": "CPC_DISC_SMM_ACTION_TEARDOWN",
    "DR206": "CPC_DISC_SILK_LICENSE_ENFORCED",
    "DR211": "CPC_DISC_REFER_METHOD_BYE",
    "DR220": "CPC_DISC_NODE_CAC_LIMIT_REACHED",
    "DR224": "CPC_DISC_MIN_SIPREC_SESSIONS_NOT_ESTABLISHED",
}

sip_cause_code_mapping = {
    # 1xx – Provisional
    "sip_100": "Trying",
    "sip_180": "Ringing",
    "sip_181": "Call Is Being Forwarded",
    "sip_182": "Queued",
    "sip_183": "Session Progress",

    # 2xx – Success
    "sip_200": "OK",
    "sip_202": "Accepted",

    # 3xx – Redirection
    "sip_300": "Multiple Choices",
    "sip_301": "Moved Permanently",
    "sip_302": "Moved Temporarily",
    "sip_305": "Use Proxy",
    "sip_380": "Alternative Service",

    # 4xx – Client Failure
    "sip_400": "Bad Request",
    "sip_401": "Unauthorized",
    "sip_402": "Payment Required",
    "sip_403": "Forbidden",
    "sip_404": "Not Found",
    "sip_405": "Method Not Allowed",
    "sip_406": "Not Acceptable",
    "sip_407": "Proxy Authentication Required",
    "sip_408": "Request Timeout",
    "sip_409": "Conflict",
    "sip_410": "Gone",
    "sip_413": "Request Entity Too Large",
    "sip_414": "Request-URI Too Long",
    "sip_415": "Unsupported Media Type",
    "sip_416": "Unsupported URI Scheme",
    "sip_420": "Bad Extension",
    "sip_421": "Extension Required",
    "sip_423": "Interval Too Brief",
    "sip_480": "Temporarily Unavailable",
    "sip_481": "Call/Transaction Does Not Exist",
    "sip_482": "Loop Detected",
    "sip_483": "Too Many Hops",
    "sip_484": "Address Incomplete",
    "sip_485": "Ambiguous",
    "sip_486": "Busy Here",
    "sip_487": "Request Terminated",
    "sip_488": "Not Acceptable Here",
    "sip_489": "Bad Event",
    "sip_491": "Request Pending",
    "sip_493": "Undecipherable",

    # 5xx – Server Failure
    "sip_500": "Server Internal Error",
    "sip_501": "Not Implemented",
    "sip_502": "Bad Gateway",
    "sip_503": "Service Unavailable",
    "sip_504": "Server Time-out",
    "sip_505": "Version Not Supported",
    "sip_513": "Message Too Large",

    # 6xx – Global Failure
    "sip_600": "Busy Everywhere",
    "sip_603": "Decline",
    "sip_604": "Does Not Exist Anywhere",
    "sip_606": "Not Acceptable",
}

start_cdr_example = 'START,ABCGSX1,0x0001042B00000012,95396749,GMT-08:00-Pacific(US),02/22/2013,17:02:12.5,5,16,511,VoIP,IP-TO-IP,BillCAN_GOW_PARTITION,,,5307520014,,0,,0,,0,,,1,ABCGSX1:NBSPUBSIP_ON_SIF93,10.158.151.66,0.0.0.0,NBS_TRUSTED_ABCASX1,,10.158.130.205:5004/10.158.130.205:5002,,10.158.151.70:5004/10.158.140.133:2224,,,,0x00020003,,,,2,"SIP,1212381174405161289093_12979976@10.158.10.170,%22Unavailable%22;tag=gK001a110b,;tag=gK02d1465e,0,,,,sip:+15307520014@10.158.130.202:5060;dtg=NBSPUBSIP_ON_SIF93;reg-info=102,,,,sip:Unavailable@10.158.10.170:5620,sip:+15307520014@10.158.130.202:5060,,,,,,,0,0,,0,0,,,,,,,,1,0,0,0,,,,",12,12,0,1,,,0x0a,15307520014,1,1,,NBSPUBSIP_ON_SIF93,"SIP,131074_79727915@10.158.151.66,%22Unavailable%22;tag=gK0251473f,;tag=7D7842DB-2113CB70,0,,,,sip:+15307520014@10.158.140.133:5060;methods=INVITE; ACK; BYE; CANCEL; OPTIONS; INFO; MESSAGE; SUBSCRIBE; NOTIFY;PRACK;UPDATE; REFER;bgid=16824600;bgt=public,,,,sip:Unavailable@10.158.151.66:5060,sip:+15307520014@10.158.140.133,,,,,,,1,1,10.158.140.133,0,0,,,,,,,,1,0,0,0,,,,",,110,,,1,1,,,2,0x00020002,0,,,,,,0,,,,1,,,,,,,6,,,,"Unavailable",2,1,1,1,16824600,,7,,,1,7,1,,,10.158.130.202,10.158.10.170,2,16,8,,,,,,16824600,,,3,0,38,TANDEM,,,,,,,13,1,,,,,,,,,,,,,,,,0,,,,,,,,0,,,"96,84,2,182",0,,,,,,,,,,,,,0,0,0,0,0,0'

stop_cdr_example = 'STOP,ABCGSX1,0x0001042B00000012,95396749,GMT-08:00-Pacific(US),02/22/2013,17:02:12.5,5,16,511,02/22/2013,17:02:20.7,6,306,16,VoIP,IP-TO-IP,BillCAN_GOW_PARTITION,,5307520010,5307520014,,0,,0,,0,5307520010,,1,ABCGSX1:NBSPUBSIP_ON_SIF93,10.158.151.66,0.0.0.0,NBS_TRUSTED_ABCASX1,,10.158.130.205:5004/10.158.130.205:5002,,10.158.151.70:5004/10.158.140.133:2224,21440,134,20640,129,,,,0x00020003,,,,,2,"SIP,1212381174405161289093_12979976@10.158.10.170,%22Unavailable%22;tag=gK001a110b,;tag=gK02d1465e,0,,,,sip:+15307520014@10.158.130.202:5060;dtg=NBSPUBSIP_ON_SIF93;reg-info=102,,,,sip:Unavailable@10.158.10.170:5620,sip:+15307520014@10.158.130.202:5060,,,,1,BYE,,0,0,,0,0,,,,,,,,1,0,0,0,,,,",12,12,0,1,,,0x0a,15307520014,1,1,,2,10,0,,NBSPUBSIP_ON_SIF93,"SIP,131074_79727915@10.158.151.66,%22Unavailable%22;tag=gK0251473f,;tag=7D7842DB-2113CB70,0,,,,sip:+15307520014@10.158.140.133:5060;methods=INVITE;ACK; BYE; CANCEL; OPTIONS; INFO; MESSAGE; SUBSCRIBE; NOTIFY; PRACK; UPDATE; REFER;bgid=16824600;bgt=public,,,,sip:Unavailable@10.158.151.66:5060,sip:+15307520014@10.158.140.133,,,,,BYE,,1,1,10.158.140.133,0,0,,,,,,,,1,0,0,0,,,,",,110,,,1,1,,,2,P:2:1,P:2:1,10,0x00020002,,,0,,,,,,0,,,,1,,,,,,,6,,,,"Unavailable",2,1,1,1,16824600,,7,,,1,7,0,306,1,,,,,10.158.130.202,10.158.10.170,4,16,8,,,,,,16824600,,,3,0,38,TANDEM,,,10,20640,129,21440,134,0,0,,16,64,,,,,,,13,1,,,,,,,,,,,,,,,,,,,,,0,9,,,,,,,,,,,,,,,"96,84,2,182",0,,,,,,,,,,,,,,,,,,,0,0,0,0,0,0'

attempt_cdr_example = 'ATTEMPT,ABCGSX1,0x0001042B00000010,95396662,GMT-08:00-Pacific(US),02/22/2013,17:02:11.6,13,0,17:02:11.8,6,21,VoIP,IP-TO-IP,BillCAN_GOW_PARTITION,,5307520010,5307520014,,0,,0,,0,5307520010,ABC_TOASX,1,ABCGSX1:NBS_TRUSTED_ABCASX1,10.158.130.202,10.158.10.170,NBSPUBSIP_ON_SIF93,,10.158.151.70:5000/127.0.0.0:5004,,10.158.130.205:5000/:0,,,,0x00000001,,,,2,2,"SIP,f86fbb68-b4d047e1-a24212c6@10.158.140.130,%22+5307520010%22;tag=59D07E6E-2A6FE7AF,;tag=gK02d14240,0,,,,sip:5307520014@10.158.151.66;user=phone,,,,sip:+5307520010@10.158.140.130,,,,,,401,,1,1,10.158.140.130,0,0,,,,,,,,1,0,0,0,,,,",12,12,0,1,,,0x0a,5307520014,1,1,,2,NBS_TRUSTED_ABCASX1,"SIP,131072_111295356@10.158.130.202,%22+5307520010%22;tag=gK025143e1,,0,,,,sip:5307520014@10.158.10.170:5620;user=phone,,,,sip:+5307520010@10.158.130.202:5060;reg-info=402,,,,,,401,,0,0,,0,0,,,,,,,,1,0,0,0,,,,",5307520010,110,,,1,1,,,2,,,,0x00020000,0,,,0,,,,,,0,,,,1,,,,,,,6,,,,"+5307520010",2,1,1,1,1,,17,02/22/2013,2,2,,7,1,401,,,,10.158.151.66,10.158.140.130,1,16,8,,,,,,,,,3,0,81,TANDEM,,,,,,,,13,1,,,,,,1,,,,,,,,,,,,,0,9,,,,,,,,,,,,"184,52,5,241",0,,,,,,,,,,,,,'
